---
- name: pip | install
  apt:
    name:
    - python-pip
    - python-setuptools
    - build-essential
    - python-dev
    - libpq-dev
    state: latest
    install_recommends: no
    force_apt_get: yes

  tags: pip

- name: pip | install patroni dependencies
  pip:
    name: "{{ item }}"
  loop:
    - python-etcd
    - wheel
  tags: pip
