---
- name: pip3 | install
  apt:
    name:
    - python3-pip
    - python3-setuptools
    - build-essential
    - python3-dev
    - libpq-dev
    state: latest
    install_recommends: no
    force_apt_get: yes
  tags: pip

#- name: pip3 | install patroni dependencies
  #pip:
    #name:
    #- wheel
  #tags: pip
