---
- name: pip3 | install
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: no
  loop:
    - python3-pip
    - python3-setuptools
    - build-essential
    - python3-dev
    - libpq-dev
  tags: pip

- name: pip3 | install patroni dependencies
  pip:
    name: "{{ item }}"
  loop:
    - python-etcd
    - wheel
  tags: pip
