---
- name: postgresql | ensure a locale exists
  locale_gen:
    name: ru_RU.UTF-8
    state: present

- name: postgresql | ca-certificates
  apt:
    name:
      - ca-certificates
    state: present
  tags: postgresql

- name: postgresql | add apt-key
  apt_key:
    id: "{{ postgresql_apt_key_id }}"
    url: "{{ postgresql_apt_key_url }}"
    state: present
  when: postgresql_apt_key_url and postgresql_apt_key_id
  tags: postgresql

- name: postgresql | add apt
  apt_repository:
    repo: "{{ postgresql_apt_repository }}"
    state: present
  when: postgresql_apt_repository is defined
  tags: postgresql

- name: postgresql | install common package
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - postgresql-common
  tags: postgresql

- name: postgresql | create createcluster.d directory
  file:
    path: /etc/postgresql-common/createcluster.d
    state: directory

- name: postgresql | disable initializing of a default postgresql cluster
  template:
    src: createcluster.conf.j2
    dest: /etc/postgresql-common/createcluster.d/createcluster.conf
  when: ansible_os_family == "Debian"
  tags: postgresql

- name: postgresql | install
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - "postgresql-{{postgresql_version}}"
    - "postgresql-client-{{postgresql_version}}"
    - "postgresql-contrib-{{postgresql_version}}"
    - python-psycopg2
    - repmgr
  tags: postgresql

- name: postgresql | stop service
  systemd:
    name: postgresql
    state: stopped
    enabled: no
  tags: postgresql

#- name: postgresql | remove data directory
  #file:
    #state: absent
    #path: "{{ postgresql_data }}"
  #when: postgresql_remove_data
  #tags: postgresql
