---
#- name: postgresql | ensure a locale exists
  #locale_gen:
    #name: ru_RU.UTF-8
    #state: present

- name: postgresql | ca-certificates
  apt:
    name:
    - ca-certificates
    - gpg
    state: present
    force_apt_get: yes

- name: postgresql | add apt-key
  apt_key:
    id: "{{ postgresql_apt_key_id }}"
    url: "{{ postgresql_apt_key_url }}"
    state: present
  when: postgresql_apt_key_url and postgresql_apt_key_id

- name: postgresql | add apt
  apt_repository:
    repo: "{{ postgresql_apt_repository }}"
    state: present
  when: postgresql_apt_repository is defined

- name: postgresql | install common package
  apt:
    name:
    - postgresql-common
    state: present
    force_apt_get: yes

- name: postgresql | create createcluster.d directory
  file:
    path: /etc/postgresql-common/createcluster.d
    state: directory

- name: postgresql | disable initializing of a default postgresql cluster
  template:
    src: createcluster.conf.j2
    dest: /etc/postgresql-common/createcluster.d/createcluster.conf
  when: ansible_os_family == "Debian"

- name: postgresql | install
  apt:
    name:
    - "postgresql-{{postgresql_version}}"
    - "postgresql-client-{{postgresql_version}}"
    - "postgresql-contrib-{{postgresql_version}}"
    - repmgr
    state: present
    update_cache: yes
    install_recommends: no
    force_apt_get: yes

#- name: postgresql | stop service
  #systemd:
    #name: postgresql
    #state: stopped
    #enabled: no

#- name: postgresql | remove data directory
  #file:
    #state: absent
    #path: "{{ postgresql_data }}"
  #when: postgresql_remove_data
